services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - dbnetwork
    ports:
      - "75432:75432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    image: 5ecommander:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    networks:
      - dbnetwork
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEVELOPMENT_GUILD_ID: ${DEVELOPMENT_GUILD_ID}
    volumes:
      - ./logs:/botlogs
    command: python -m src.bot.main


networks:
  dbnetwork:
    driver: bridge

volumes:
  postgres_data:
