from src.database.database import Database
from src.definitions.regions import *
from src.definitions.creatures import *

start_condition = Database.StartCondition(
    {
        "channel_id": 0,
        "max_orders": 3,
        "order_recharge": 30,
        "max_magic": 10,
        "magic_recharge": 30,
        "max_cards": 10,
        "card_recharge": 30,
        "region_recharge": 10,
        "creature_recharge": 10,
        "free_protection": 30,
        "free_expire": 180,
        "conflict_duration": 60 * 5,
    },
    [
        RoyalGift(),
        CourtPolitics(),
        Delegation(),
        ArtefactFence(),
        Collections(),
        Laborers(),
        Cave(),
        Dungeon(),
        HiddenLair(),
        Ritual(),
        Library(),
        BindingSpell(),
        HiddenCache(),
        Hunt(),
        Abandon(),
    ],
    [
        Servant(),
        Commoner(),
        NoviceAdventurer(),
        NoviceMage(),
        LoyalSquire(),
        Herald(),
        Local(),
        Guide(),
        MagicStudent(),
        Farmer(),
        Ambassador(),
        Trader(),
        Explorer(),
        Mentor(),
        Hunter(),
        Messenger(),
        Towncrier(),
        Quartermaster(),
        ArcaneTutor(),
        Druid(),
        RetiredGeneral(),
        SwordSmith(),
        Scout(),
        Librarian(),
        Nymph(),
        Soldier(),
        Bandit(),
        Paladin(),
        ArcaneGolem(),
        WildDrake(),
        Duke(),
        Spy(),
        Drow(),
        Alchemist(),
        TalkingCat(),
        Tavernkeeper(),
        Mimic(),
        GreatArcaneWyrm(),
        RedDragon(),
        Saboteur(),
    ],
    [
        Servant(),
        Servant(),
        Commoner(),
        Commoner(),
        Commoner(),
        NoviceAdventurer(),
        NoviceAdventurer(),
        NoviceMage(),
        LoyalSquire(),
    ],
)
